package testDllProject;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.ochafik.lang.jnaerator.runtime.Union;
import java.util.Arrays;
import java.util.List;
/**
 * --------------------- \u0424\u043e\u0440\u043c\u0430\u0442 \u0431\u0443\u0444\u0435\u0440\u0430, \u0432\u043e\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u043c\u043e\u0433\u043e \u043a\u043e\u043c\u0430\u043d\u0434\u0430\u043c\u0438 \u0447\u0442\u0435\u043d\u0438\u044f<br>
 * <i>native declaration : line 125</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class _Otvet extends Union<_Otvet, _Otvet.ByValue, _Otvet.ByReference > {
	/** \u041e\u0442\u0432\u0435\u0442 - \u043a\u043e\u0434 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f */
	public byte KodSoob;
	/**
	 * \u0414\u0430\u043d\u043d\u044b\u0435 \u0441\u043b\u0443\u0436\u0435\u0431\u043d\u043e\u0433\u043e \u043a\u0430\u043d\u0430\u043b\u0430<br>
	 * C type : _SK
	 */
	public _SK Slug_Kanal;
	/**
	 * \u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u0437\u0430\u043f\u0440\u043e\u0441 ReadMessage<br>
	 * C type : _MessageBuffer
	 */
	public _MessageBuffer MessageBuffer;
	/**
	 * \u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u0437\u0430\u043f\u0440\u043e\u0441 \u0442\u0435\u043a \u0432\u0440\u0435\u043c\u0435\u043d\u0438 \u0434\u0435\u043a\u043e\u0434\u0435\u0440\u0430<br>
	 * C type : _GetCurrentTime
	 */
	public _GetCurrentTime GetCurrentTimeStruct;
	/**
	 * \u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u0434\u0440\u0443\u0433\u0438\u0435 \u0437\u0430\u043f\u0440\u043e\u0441\u044b \u0434\u0430\u043d\u043d\u044b\u0445<br>
	 * C type : _Data
	 */
	public _Data Data;
	/** <i>native declaration : line 128</i> */
	public static class _MessageBuffer extends Structure<_MessageBuffer, _MessageBuffer.ByValue, _MessageBuffer.ByReference > {
		/** \u0442\u0438\u043f \u0434\u0430\u043d\u043d\u044b\u0445 = 103 */
		public byte KodSoob;
		/**
		 * \u0432\u0440\u0435\u043c\u044f<br>
		 * C type : UINT64
		 */
		public long TimeInt64;
		/**
		 * \u041c\u0430\u0441\u0441\u0438\u0432 \u043a\u043e\u0434\u043e\u0432 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0439 (\u043e\u0442 1 \u0434\u043e 50)<br>
		 * C type : char[1]
		 */
		public byte[] Messages = new byte[1];
		public _MessageBuffer() {
			super();
		}
		protected List<String> getFieldOrder() {
			return Arrays.asList("KodSoob", "TimeInt64", "Messages");
		}
		/**
		 * @param KodSoob \u0442\u0438\u043f \u0434\u0430\u043d\u043d\u044b\u0445 = 103<br>
		 * @param TimeInt64 \u0432\u0440\u0435\u043c\u044f<br>
		 * C type : UINT64<br>
		 * @param Messages \u041c\u0430\u0441\u0441\u0438\u0432 \u043a\u043e\u0434\u043e\u0432 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0439 (\u043e\u0442 1 \u0434\u043e 50)<br>
		 * C type : char[1]
		 */
		public _MessageBuffer(byte KodSoob, long TimeInt64, byte Messages[]) {
			super();
			this.KodSoob = KodSoob;
			this.TimeInt64 = TimeInt64;
			if ((Messages.length != this.Messages.length)) 
				throw new IllegalArgumentException("Wrong array size !");
			this.Messages = Messages;
		}
		protected ByReference newByReference() { return new ByReference(); }
		protected ByValue newByValue() { return new ByValue(); }
		protected _MessageBuffer newInstance() { return new _MessageBuffer(); }
		public static _MessageBuffer[] newArray(int arrayLength) {
			return Structure.newArray(_MessageBuffer.class, arrayLength);
		}
		public static class ByReference extends _MessageBuffer implements Structure.ByReference {
			
		};
		public static class ByValue extends _MessageBuffer implements Structure.ByValue {
			
		};
	};
	/** <i>native declaration : line 133</i> */
	public static class _GetCurrentTime extends Structure<_GetCurrentTime, _GetCurrentTime.ByValue, _GetCurrentTime.ByReference > {
		/**
		 * \u0432\u0440\u0435\u043c\u044f<br>
		 * C type : UINT64
		 */
		public long TimeInt64;
		public _GetCurrentTime() {
			super();
		}
		protected List<String> getFieldOrder() {
			return Arrays.asList("TimeInt64");
		}
		/**
		 * @param TimeInt64 \u0432\u0440\u0435\u043c\u044f<br>
		 * C type : UINT64
		 */
		public _GetCurrentTime(long TimeInt64) {
			super();
			this.TimeInt64 = TimeInt64;
		}
		protected ByReference newByReference() { return new ByReference(); }
		protected ByValue newByValue() { return new ByValue(); }
		protected _GetCurrentTime newInstance() { return new _GetCurrentTime(); }
		public static _GetCurrentTime[] newArray(int arrayLength) {
			return Structure.newArray(_GetCurrentTime.class, arrayLength);
		}
		public static class ByReference extends _GetCurrentTime implements Structure.ByReference {
			
		};
		public static class ByValue extends _GetCurrentTime implements Structure.ByValue {
			
		};
	};
	/** <i>native declaration : line 136</i> */
	public static class _Data extends Structure<_Data, _Data.ByValue, _Data.ByReference > {
		/**
		 * \u0432\u0440\u0435\u043c\u044f<br>
		 * C type : UINT64
		 */
		public long TimeInt64;
		/**
		 * \u0414\u0430\u043d\u043d\u044b\u0435 \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u0439<br>
		 * C type : _MeasuringData
		 */
		public _MeasuringData MD;
		/** <i>native declaration : line 138</i> */
		public static class _MeasuringData extends Union<_MeasuringData, _MeasuringData.ByValue, _MeasuringData.ByReference > {
			/** \u0414\u0430\u043d\u043d\u044b\u0435 \u0434\u043b\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u044b READ_BASE */
			public float OsnIzmVel;
			/** \u0414\u0430\u043d\u043d\u044b\u0435 \u0434\u043b\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u044b READ_TEMPER */
			public float Temper;
			/**
			 * \u0414\u0430\u043d\u043d\u044b\u0435 \u0434\u043b\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u044b READ_SPEED<br>
			 * C type : _RS
			 */
			public _RS RS;
			/**
			 * \u0414\u0430\u043d\u043d\u044b\u0435 \u0434\u043b\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u044b READ_COMPLEX<br>
			 * C type : _RC
			 */
			public _RC RC;
			/** <i>native declaration : line 141</i> */
			public static class _RS extends Structure<_RS, _RS.ByValue, _RS.ByReference > {
				/** \u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c */
				public float Skorost;
				/** \u041c\u043e\u0449\u043d\u043e\u0441\u0442\u044c */
				public float Moschnost;
				public _RS() {
					super();
				}
				protected List<String > getFieldOrder() {
					return Arrays.asList("Skorost", "Moschnost");
				}
				/**
				 * @param Skorost \u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c<br>
				 * @param Moschnost \u041c\u043e\u0449\u043d\u043e\u0441\u0442\u044c
				 */
				public _RS(float Skorost, float Moschnost) {
					super();
					this.Skorost = Skorost;
					this.Moschnost = Moschnost;
				}
				protected ByReference newByReference() { return new ByReference(); }
				protected ByValue newByValue() { return new ByValue(); }
				protected _RS newInstance() { return new _RS(); }
				public static _RS[] newArray(int arrayLength) {
					return Structure.newArray(_RS.class, arrayLength);
				}
				public static class ByReference extends _RS implements Structure.ByReference {
					
				};
				public static class ByValue extends _RS implements Structure.ByValue {
					
				};
			};
			/** <i>native declaration : line 145</i> */
			public static class _RC extends Structure<_RC, _RC.ByValue, _RC.ByReference > {
				/** \u043e\u0441\u043d\u043e\u0432\u043d\u0430\u044f \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u043d\u0430\u044f \u0432\u0435\u043b\u0438\u0447\u0438\u043d\u0430 (\u043c\u043e\u043c\u0435\u043d\u0442 \u0438\u043b\u0438 \u0441\u0438\u043b\u0430 */
				public float OsnIzmVel;
				/** \u0422\u0435\u043c\u043f\u0435\u0440\u0430\u0442\u0443\u0440\u0430 */
				public float Temper;
				/** \u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c */
				public float Skorost;
				/** \u041c\u043e\u0449\u043d\u043e\u0441\u0442\u044c */
				public float Moschnost;
				public _RC() {
					super();
				}
				protected List<String > getFieldOrder() {
					return Arrays.asList("OsnIzmVel", "Temper", "Skorost", "Moschnost");
				}
				/**
				 * @param OsnIzmVel \u043e\u0441\u043d\u043e\u0432\u043d\u0430\u044f \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u043d\u0430\u044f \u0432\u0435\u043b\u0438\u0447\u0438\u043d\u0430 (\u043c\u043e\u043c\u0435\u043d\u0442 \u0438\u043b\u0438 \u0441\u0438\u043b\u0430<br>
				 * @param Temper \u0422\u0435\u043c\u043f\u0435\u0440\u0430\u0442\u0443\u0440\u0430<br>
				 * @param Skorost \u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c<br>
				 * @param Moschnost \u041c\u043e\u0449\u043d\u043e\u0441\u0442\u044c
				 */
				public _RC(float OsnIzmVel, float Temper, float Skorost, float Moschnost) {
					super();
					this.OsnIzmVel = OsnIzmVel;
					this.Temper = Temper;
					this.Skorost = Skorost;
					this.Moschnost = Moschnost;
				}
				protected ByReference newByReference() { return new ByReference(); }
				protected ByValue newByValue() { return new ByValue(); }
				protected _RC newInstance() { return new _RC(); }
				public static _RC[] newArray(int arrayLength) {
					return Structure.newArray(_RC.class, arrayLength);
				}
				public static class ByReference extends _RC implements Structure.ByReference {
					
				};
				public static class ByValue extends _RC implements Structure.ByValue {
					
				};
			};
			public _MeasuringData() {
				super();
			}
			/**
			 * @param RS \u0414\u0430\u043d\u043d\u044b\u0435 \u0434\u043b\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u044b READ_SPEED<br>
			 * C type : _RS
			 */
			public _MeasuringData(_RS RS) {
				super();
				this.RS = RS;
				setType(_RS.class);
			}
			/**
			 * @param RC \u0414\u0430\u043d\u043d\u044b\u0435 \u0434\u043b\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u044b READ_COMPLEX<br>
			 * C type : _RC
			 */
			public _MeasuringData(_RC RC) {
				super();
				this.RC = RC;
				setType(_RC.class);
			}
			/** @param OsnIzmVel_or_Temper \u0414\u0430\u043d\u043d\u044b\u0435 \u0434\u043b\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u044b READ_BASE, or \u0414\u0430\u043d\u043d\u044b\u0435 \u0434\u043b\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u044b READ_TEMPER */
			public _MeasuringData(float OsnIzmVel_or_Temper) {
				super();
				this.Temper = this.OsnIzmVel = OsnIzmVel_or_Temper;
				setType(Float.TYPE);
			}
			protected ByReference newByReference() { return new ByReference(); }
			protected ByValue newByValue() { return new ByValue(); }
			protected _MeasuringData newInstance() { return new _MeasuringData(); }
			public static _MeasuringData[] newArray(int arrayLength) {
				return Union.newArray(_MeasuringData.class, arrayLength);
			}
			public static class ByReference extends _MeasuringData implements Structure.ByReference {
				
			};
			public static class ByValue extends _MeasuringData implements Structure.ByValue {
				
			};
		};
		public _Data() {
			super();
		}
		protected List<String> getFieldOrder() {
			return Arrays.asList("TimeInt64", "MD");
		}
		/**
		 * @param TimeInt64 \u0432\u0440\u0435\u043c\u044f<br>
		 * C type : UINT64<br>
		 * @param MD \u0414\u0430\u043d\u043d\u044b\u0435 \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u0439<br>
		 * C type : _MeasuringData
		 */
		public _Data(long TimeInt64, _MeasuringData MD) {
			super();
			this.TimeInt64 = TimeInt64;
			this.MD = MD;
		}
		protected ByReference newByReference() { return new ByReference(); }
		protected ByValue newByValue() { return new ByValue(); }
		protected _Data newInstance() { return new _Data(); }
		public static _Data[] newArray(int arrayLength) {
			return Structure.newArray(_Data.class, arrayLength);
		}
		public static class ByReference extends _Data implements Structure.ByReference {
			
		};
		public static class ByValue extends _Data implements Structure.ByValue {
			
		};
	};
	public _Otvet() {
		super();
	}
	/**
	 * @param GetCurrentTimeStruct \u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u0437\u0430\u043f\u0440\u043e\u0441 \u0442\u0435\u043a \u0432\u0440\u0435\u043c\u0435\u043d\u0438 \u0434\u0435\u043a\u043e\u0434\u0435\u0440\u0430<br>
	 * C type : _GetCurrentTime
	 */
	public _Otvet(_GetCurrentTime GetCurrentTimeStruct) {
		super();
		this.GetCurrentTimeStruct = GetCurrentTimeStruct;
		setType(_GetCurrentTime.class);
	}
	/**
	 * @param Data \u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u0434\u0440\u0443\u0433\u0438\u0435 \u0437\u0430\u043f\u0440\u043e\u0441\u044b \u0434\u0430\u043d\u043d\u044b\u0445<br>
	 * C type : _Data
	 */
	public _Otvet(_Data Data) {
		super();
		this.Data = Data;
		setType(_Data.class);
	}
	/** @param KodSoob \u041e\u0442\u0432\u0435\u0442 - \u043a\u043e\u0434 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f */
	public _Otvet(byte KodSoob) {
		super();
		this.KodSoob = KodSoob;
		setType(Byte.TYPE);
	}
	/**
	 * @param MessageBuffer \u041e\u0442\u0432\u0435\u0442 \u043d\u0430 \u0437\u0430\u043f\u0440\u043e\u0441 ReadMessage<br>
	 * C type : _MessageBuffer
	 */
	public _Otvet(_MessageBuffer MessageBuffer) {
		super();
		this.MessageBuffer = MessageBuffer;
		setType(_MessageBuffer.class);
	}
	/**
	 * @param Slug_Kanal \u0414\u0430\u043d\u043d\u044b\u0435 \u0441\u043b\u0443\u0436\u0435\u0431\u043d\u043e\u0433\u043e \u043a\u0430\u043d\u0430\u043b\u0430<br>
	 * C type : _SK
	 */
	public _Otvet(_SK Slug_Kanal) {
		super();
		this.Slug_Kanal = Slug_Kanal;
		setType(_SK.class);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected _Otvet newInstance() { return new _Otvet(); }
	public static _Otvet[] newArray(int arrayLength) {
		return Union.newArray(_Otvet.class, arrayLength);
	}
	public static class ByReference extends _Otvet implements Structure.ByReference {
		
	};
	public static class ByValue extends _Otvet implements Structure.ByValue {
		
	};
}
